### ISSUE TITLE
mvn2nix fails, probably because openjdk11 instead of maven-compiler 1.8 is used

### ISSUE THREAD

**Issue by ngiger** [fzakaria/mvn2nix#34]
I am trying to build https://github.com/elexis/elexis-3-core/ on a nixos 20.09 machine.
Running in the checkout `mvn2nix -v > mvn2nix-lock.json 2> mvn2nix.log` fails with many compilation errors complaining about `The import javax.xml.bind cannot be resolved`. This is the same error, when I run it in Debian buster with maven 3.6.3 and using java from openjdk-11.
Is there any possibity to specify the jdk used by mvn2nix?

**Comment by fzakaria** [comment]
I had a WIP for this you can checkout: https://github.com/fzakaria/mvn2nix/blob/jdk8-support/overlay.nix#L6 
I was going to add to the overlay, additional versions of mvn2nix.

I've been meaning to take another stab at this; Maven is quite the behemoth to try and tackle :)

**Comment by rafael-brandao** [comment]
I have a similar error running mvn2nix in my JDK8 maven project, but I've got this error:

```
❯ nix run github:fzakaria/mvn2nix#mvn2nix
Failed to execute goals [[package]]. Exit code: 1
```

JDK8 support would be highly appreciated.

**Comment by fzakaria** [comment]
I landed the PR above @rafael-brandao please sync your commit.
Please take a look at https://github.com/fzakaria/mvn2nix/pull/39 

Example would be:
```bash
~/code/github.com/fzakaria/mvn2nix/result/bin/mvn2nix \
    --jdk $(nix build nixpkgs.jdk8 && nix eval nixpkgs.jdk8.home --raw) \
    -vvv --goals package 
```

**Comment by ngiger** [comment]
I used my checkout of git@github.com:elexis/elexis-3-core.git (at commit 643f729c76ef273cd3eccf3f1fd0765591883de3) to test it against commit ea21cfe97069feee55fa307ca9b125616c1fa84f of git@github.com:fzakaria/mvn2nix.git

Using `/opt/src/mvn2nix/result/bin/mvn2nix --jdk /nix/store/lsihmq55fdi8894rznz90i92a10lza1k-openjdk-headless-8u272-b10/ --verbose` it failed after 5 minutes with the following lines:

<pre>
2021-09-29 10:21:11,579 [Thread-1] INFO : [INFO] BUILD SUCCESS
2021-09-29 10:21:11,579 [Thread-1] INFO : [INFO] ------------------------------------------------------------------------
2021-09-29 10:21:11,579 [Thread-1] INFO : [INFO] Total time:  05:04 min
2021-09-29 10:21:11,579 [Thread-1] INFO : [INFO] Finished at: 2021-09-29T10:21:11+02:00
2021-09-29 10:21:11,579 [Thread-1] INFO : [INFO] ------------------------------------------------------------------------
java.lang.NullPointerException
java.lang.NullPointerException
at com.fzakaria.mvn2nix.maven.Maven.lambda$collectAllArtifactsInLocalRepository$8(Maven.java:138)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
at com.fzakaria.mvn2nix.maven.Maven.collectAllArtifactsInLocalRepository(Maven.java:165)
at com.fzakaria.mvn2nix.cmd.Maven2nix.call(Maven2nix.java:76)
at com.fzakaria.mvn2nix.cmd.Maven2nix.call(Maven2nix.java:33)
at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
at picocli.CommandLine.access$1100(CommandLine.java:145)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
at com.fzakaria.mvn2nix.cmd.LoggingMixin.executionStrategy(LoggingMixin.java:109)
at picocli.CommandLine.execute(CommandLine.java:2058)
at com.fzakaria.mvn2nix.Main.main(Main.java:19)
</pre>

**Comment by ngiger** [comment]
I could work around the NPE with the attached diff
[issue_34.diff](https://github.com/fzakaria/mvn2nix/files/7251170/issue_34.diff.txt)

But it fails, for jars like p2.osgi.bundle:org.eclipse.equinox.p2.console
I think the main problem is that Eclipse's P2 repositories are not handled as they are not found in a maven repository.
